### ISSUE TITLE
undefined - undefined - Right-hand side of 'instanceof' is not an object

### ISSUE THREAD

**Issue by xfishernet** [lmelon/homebridge-vaillant-vrc9xx#13]
[02/09/2021, 07:40:59] [VaillantVRC9xx]   > undefined - undefined - Right-hand side of 'instanceof' is not an object
[02/09/2021, 07:41:03] [VaillantVRC9xx]   > retry #2
[02/09/2021, 07:41:03] [VaillantVRC9xx] {
  error: true,
  status: undefined,
  body: "Right-hand side of 'instanceof' is not an object",
  response: TypeError: Right-hand side of 'instanceof' is not an object
      at fetch (/usr/lib/node_modules/homebridge-vaillant-vrc9xx/node_modules/node-fetch-cookies/src/index.mjs:40:29)
      at HTTPClient.fetch (/usr/lib/node_modules/homebridge-vaillant-vrc9xx/src/api/HttpClient.mjs:25:36)
      at HTTPClient.execute (/usr/lib/node_modules/homebridge-vaillant-vrc9xx/src/api/HttpClient.mjs:61:3

**Comment by tritter** [comment]
@xfishernet try my fork: `sudo npm i -g tritter/homebridge-vaillant-vrc9xx`

**Comment by xfishernet** [comment]
> @xfishernet try my fork: `sudo npm i -g tritter/homebridge-vaillant-vrc9xx`

Big Thanks!! Now it works great!
